name: MCLiveTrap
version: 1.0.0
main: jp.example.mclivetrap.MCLiveTrapPlugin
api-version: "1.20"
author: example
description: Phase1 HTTP webhook receiver for TikTok events

commands:
  mclivetrap:
    description: Create a trap box
    usage: /mclivetrap  <create|clear|remove|list>
