# python:3.12-slim をベース
FROM python:3.12-slim

# 作業ディレクトリ
WORKDIR /app

# 依存関係インストール
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Python ファイルと config ディレクトリを /app に丸ごとコピー
COPY app/*.py ./
COPY app/config ./config/

CMD ["python", "-u", "dummy_main.py"]
